# Generated by Django 4.2 on 2026-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('satisfaction', models.CharField(choices=[('SP', 'Sangat Puas'), ('P', 'Puas'), ('CP', 'Cukup Puas'), ('TP', 'Tidak Puas'), ('STP', 'Sangat Tidak Puas')], max_length=3)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
