# Generated by Django 4.2 on 2026-02-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='agree_ethics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='agree_law',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='agree_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='ap_ip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='survey',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
